language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run compile-gulpfile
  - npm run bundle
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAGES_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: src/html
